= キャンバスのカスタマイズ
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


環境、タグ、サービスの検索条件を適用して、Visualizer のキャンバスに何が表示されるのかを選択できます。
これにより、アプリケーションのグラフに表示したくないノードを非表示にできます。
検索条件はカスケード設計であるため、選択された環境またはタグに属さないすべてのノードは自動的にサービスのリストで非表示になります。

*[Show dependents and dependencies (連動と連動関係を表示)]* を切り替えると、サービスと、選択したタグが含まれるノードとサービスの連動関係が表示されます。
*[View (ビュー)]* カードとキャンバスが更新され、現在の選択内容が表示されます。

Visualizer エディタでは、定義済みビューを保存できるため、Visualizer ユーザはそれらのビューにアクセスできます。
Anypoint Visualizer を閉じて後でキャンバスを再読み込みすると、最後にアクセスしたビューが表示されます。

== レイヤ

Anypoint Visualizer によって提供されるデフォルトのレイヤのいずれかを使用することも、カスタムレイヤを追加してネットワークのアプリケーションの視覚表現を作成することもできます。

詳細は、xref:layers.adoc[「Anypoint Visualizer でのレイヤの使用」]を参照してください。

== タグ

タグは、API、アプリケーション、プロキシ、または他のサービスに追加できます。これにより、タグを検索条件として使用してビューを調整できます。

詳細は、xref:use-tags-in-visualizer.adoc[「Anypoint Visualizer でのタグの使用」]を参照してください。

== ビュー

Visualizer エディタでは、絞り込まれた環境とタグに基づいてビューが定義されます。これらの定義済みビューは自動的に検出でき、含まれる環境の権限を持つすべての Visualizer ユーザが使用できます。

詳細は、xref:view.adoc[「Visualizer ビュー」]を参照してください。