= Anypoint Visualizer でのアプリケーションデータの収集方法
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Visualizer は、実行中のアプリケーション、API、およびプロキシからランタイム情報を収集し、そのすべての連動関係を検出します。収集された情報には、着信要求の IP アドレスと URL (パラメータなし)、および発信要求の URL (パラメータなし) と一部のヘッダー値が含まれます。この情報は、データベースに暗号化されて保存されます。

[%header%autowidth.spread]
|===
| メタデータ | 説明
| node_info | ノードに関する一般情報。
| org_id | ノードがデプロイされている組織。
| ip | ノードの IP アドレス。
| type | ノードが API か Mule アプリケーションかを特定します。
| deployment_id | アプリケーションまたは API のハッシュを指定する内部 ID。
| app_name | アプリケーションの名前。
| url | アプリケーションの完全修飾ドメイン名。
|===

== アプリケーションのデータ収集の無効化

Anypoint Visualizer でメタデータを収集するために使用されるエージェントは、パフォーマンスに影響する可能性があります。 

=== CloudHub のパフォーマンスへの潜在的な影響の軽減

CloudHub で実行されるアプリケーションのパフォーマンスへの潜在的な影響を軽減するには、データ収集を無効にします。

==== 2019 年 3 月 22 日より前にリリースされた Mule バージョン 4 または 2019 年 4 月 5 日より前にリリースされた Mule バージョン 3.9 のデータ収集を無効にする

CloudHub で実行されるアプリケーションのパフォーマンスへの潜在的な影響を軽減するには、次のアプリケーションプロパティを設定します。

. アプリケーションプロパティ `anypoint.platform.config.visualizer.agent.enabled=false` を設定します。
. アプリケーションを再デプロイします。

==== 2019 年 3 月 22 日以降にリリースされた Mule バージョン 4 または 2019 年 4 月 5 日以降にリリースされた Mule バージョン 3 のデータ収集を無効にする

CloudHub で実行されるアプリケーションのパフォーマンスへの潜在的な影響を軽減するには、Monitoring エージェントを無効にします。

. ​*​「Anypoint Monitoring User (Anypoint Monitoring ユーザ)」​*​権限を持つユーザであることを確認します。
. Anypoint Platform にサインインし、*[Anypoint Monitoring]* をクリックします。
. *[Settings (設定)]* をクリックします。
. *[CloudHub]* を選択します。
. *[Environment (環境)]* ドロップダウンリストから、環境を選択します。
. *[List of resources in <Environment Name> (<環境名> のリソースのリスト)]* で、メトリクスを表示するアプリケーションを検索します。
. アプリケーションの横にある *[Disable & Apply (無効化 & 適用)]* をクリックして、アプリケーションの監視を無効にします。

=== スタンドアロン Mule および Runtime Fabric のパフォーマンスへの潜在的な影響の軽減

Visualizer では、スタンドアロン Mule および Runtime Fabric デプロイメントで機能する追加のヘッダー挿入が必要です。スタンドアロン Mule 4.1.x で実行されるアプリケーションのパフォーマンスへの潜在的な影響を軽減するために、ヘッダー挿入はデフォルトで無効になっています。 

[NOTE]
Runtime Fabric ではアプリケーションレベルでヘッダー挿入を有効にする必要がありますが、スタンドアロン Mule デプロイメントではアプリケーションレベルではなくサーバレベルでヘッダー挿入を有効にする必要があります。 

Mule 3 のヘッダー挿入を無効にするには、次のプロパティを設定します。 

----
anypoint.platform.config.analytics.agent.header_injection.disabled=true
----

また、スタンドアロン Mule で実行されるアプリケーションのパフォーマンスへの潜在的な影響を軽減するため、次のいずれかを実行できます。

* Anypoint Monitoring エージェントがインストールされていないサーバにアプリケーションをデプロイする。
* 特定のサーバのデータ収集を無効にする。サーバと、そのサーバにデプロイされたすべてのアプリケーションのデータ収集を無効にするには、アプリケーションレベルではなくサーバレベルで次のプロパティを設定します。 
+
----
anypoint.platform.config.analytics.agent.disabled=true 
----

[NOTE]
これにより、サーバのアプリケーションの監視も無効になります。
