= Visualizer アプリケーションネットワーク
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Visualizer を使用して、アプリケーションネットワークのグラフを表示します。

アプリケーションネットワークのトポロジは、Anypoint Visualizer によって自動的に生成されます。視覚化を見やすくするため、コンシューマノード (アウトバウンド接続のみのノード) が上部に表示され、すべてのバックエンドシステム (インバウンド接続のみのノード) が下部に表示されます。コンシューマノードで `ClientId` が検出された場合、`ClientId` でグループ化されます。それ以外の場合、*[External Traffic (外部トラフィック)]* ノードの下でグループ化されます。
 `ClientId` が検出されるには、対象の `application/API/proxy` に *[Client Id enforcement (クライアント ID 適用)]* ポリシーが設定されている必要があります。

グラフを表示または変更するときに、Anypoint Visualizer で次の機能を使用できます。

* ズームコントロール: キャンバスの右下隅にあるズームインボタン、ズームアウトボタン、サイズに合わせたズームボタンを使用して、ズームを制御します。スクロールを使用してズームインおよびズームアウトすることもできます。
* 視覚化のパン: キャンバスをクリックしてドラッグし、視覚化をパンします。

== 組織のアプリケーションネットワークの表示

. Management Center から、*[Visualizer]* を選択します。
+
Visualizer が使用できない場合は、システム管理者に連絡して、アプリケーションにアクセスするための適切な権限があることを確認してください。

. *[View (ビュー)]* カードの環境検索条件で、環境を選択します。
+
Anypoint Visualizer には、参照権限がある環境のみが表示されます。

. 表示するビジネスグループのチェックボックスをクリックします。

組織と環境グループを選択したら、Anypoint Visualizer にアプリケーションネットワークのグラフが表示されます。

== ネットワーク内のすべてのノードに関する情報の表示

*[Metric (メトリクス)]* カードのオプションを使用して、アプリケーションネットワーク内のすべてのノードについて表示するメトリクスと時間枠を選択します。
*[Metric (メトリクス)]* セクションで、次のメトリクスのいずれかを選択できます。

* *Inbound connections (インバウンド接続)*
* *Errors count (エラー数)*
* *avg. response time (平均応答時間)*
* *avg. throughput (平均スループット)*
* *Avg. CPU consumption (平均 CPU 消費量)*
* *avg. memory utilization (平均メモリ使用量)*

*[Time Range (時間範囲)]* セクションでは、選択したメトリクスの平均値の計算に使用される時間枠を選択できます。

数値が長くなることを避けるために、Anypoint Visualizer は単位のプレフィックスを使用してビューを簡略化します。次に例を示します。

|===
| Avg throughput (平均スループット) | 66.7m TPM | 6,670 万トランザクション/分 | 0.0667 TPM
|===
https://en.wikipedia.org/wiki/Metric_prefix[メトリクスプレフィックスの簡単な説明はここ]にありますが、Anypoint Visualizer では、*u* は *μ* ではなくマイクロを表します。

== ネットワーク内の 1 つのノードに関する情報の表示

グラフ内のノードを選択すると、そのノードとその連動関係スタックが強調表示され、接続されていないすべてのノードは使用できなくなります。Anypoint Visualizer のカードには、ノードに関する情報が表示されます。このカードは次のタブに分割されています。

*[Details (詳細)]* タブには、以下が含まれます。
* *Details (詳細)*: ノードに関する情報が表示されます。
* *Customization (カスタマイズ)*: ノードが割り当てられているレイヤとそのノードに割り当てられているタグに関する情報が表示されます。このセクションからノードの表示名を編集したり、レイヤやタグを変更したりできます。

*[Monitoring (監視)]* タブには、以下が含まれます。
* *Metrics summary (メトリクスの概要)*: 選択されたノードで監視しているメトリクスが表示されます。メトリクスには、[Errors count (エラー数)]、[avg. response time (平均応答時間)]、[avg. throughput (平均スループット)]、[avg. CPU consumption (平均 CPU 消費量)]、[avg. memory utilization (平均メモリ使用量)] があります。
* *Metrics chart (メトリクスチャート)*: *[Metric (メトリクス)]* カードで選択したメトリクスの時系列グラフが表示されます。


*[Search services (サービスを検索)]* テキスト項目で、ノード (サービス) を検索できます。名前に検索語が含まれるサービスは強調表示され、他のサービスは薄く表示されます。

== ネットワーク内の接続に関する情報の表示

グラフ内の接続を選択すると、Anypoint Visualizer のカードにその接続に関する基本情報が表示されます。
カードでは、表示名を編集できます。これにより、キャンバスのエッジに名前が追加されます。

[NOTE]
サービス間に表示されるエッジはアクティブです。つまり、過去 7 日間にトラフィックがあった場合にのみ表示されます。非アクティブなエッジはキャンバスに表示されません。


[[export-view]]
== ネットワークビューのエクスポート

キャンバスに表示されているネットワークのビューを PNG ファイルにエクスポートできます。

* 検索条件を使用してビューをカスタマイズしている場合、カスタマイズされたネットワークトポロジがエクスポートされる。
* メトリクスや期間を選択している場合、それらの設定がエクスポートに反映される。

ネットワークのビューを PNG としてエクスポートするには、右下のズームコントロールの横にある *[Export as Image (画像としてエクスポート)]* ボタンをクリックします。

== 関連情報

* xref:layers.adoc[Anypoint Visualizer でのレイヤの使用]
* xref:use-tags-in-visualizer.adoc[Anypoint Visualizer でのタグの使用]
